apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gcpcloudtest-ddns-net
spec:
  secretName: gcpcloudtest-ddns-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gcpcloudtest.ddns.net
  dnsNames:
    - gcpcloudtest.ddns.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - gcpcloudtest.ddns.net